env:
  browser: true
  es6: true
  node: true
  jest: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
parser: '@typescript-eslint/parser'
plugins:
- '@typescript-eslint'
- 'jest'
extends:
- 'eslint:recommended'
- 'plugin:@typescript-eslint/recommended'
rules: {}
